name: Trigger Sig's CI
on:
  repository_dispatch:
    types: [solfuzz_main]

jobs:
  kick_ci:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch SigFuzz CI
        run: |
          curl -L \
          -X POST \
          https://api.github.com/repos/Syndica/sig/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -H "Authorization: Bearer ${{ secrets.PAT }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          --data '{"event_type": "shim"}'
